
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.util.Scanner;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author hpaulo
 */
public class MenuOpcoes extends javax.swing.JFrame {
    public static Scanner ler = new Scanner(System.in);
    public static String login = Login.login;

    /**
     * Creates new form MenuOpcoes
     */
    Login log;
    public MenuOpcoes() {
        initComponents();
        if (log==null)
            log = new Login();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnMostrarUsers = new javax.swing.JButton();
        btnEliminarUser = new javax.swing.JButton();
        btnMostrarDadosUser = new javax.swing.JButton();
        btnEditarDadosUser = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnMostrarUsers.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMostrarUsers.setText("Mostrar Utilizadores Registados");
        btnMostrarUsers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarUsersActionPerformed(evt);
            }
        });

        btnEliminarUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEliminarUser.setText("Eliminar Utilizador");
        btnEliminarUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarUserActionPerformed(evt);
            }
        });

        btnMostrarDadosUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnMostrarDadosUser.setText("Visualizar Dados Utilizador");
        btnMostrarDadosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarDadosUserActionPerformed(evt);
            }
        });

        btnEditarDadosUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnEditarDadosUser.setText("Editar Dados Utilizador");
        btnEditarDadosUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarDadosUserActionPerformed(evt);
            }
        });

        btnSair.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(180, 180, 180)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnMostrarUsers, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEliminarUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnMostrarDadosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnEditarDadosUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(180, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnSair, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(90, 90, 90)
                .addComponent(btnMostrarUsers)
                .addGap(50, 50, 50)
                .addComponent(btnEliminarUser)
                .addGap(50, 50, 50)
                .addComponent(btnMostrarDadosUser)
                .addGap(50, 50, 50)
                .addComponent(btnEditarDadosUser)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(btnSair)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarDadosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarDadosUserActionPerformed
        String [] dados = {"Password: ", "Nome: ", "Email: ", "Morada: ", "Telefone: ", "NIF: "}; 
        int i = 0;
            try {
                File ficheiro = new File(login+".txt");
                FileReader fr = new FileReader(ficheiro);
                BufferedReader br = new BufferedReader(fr);
                System.out.println("Dados do utilizador: "+login);
                while(br.ready()){
                    System.out.println(dados[i]);                    
                    String linha = br.readLine();
                    System.out.println(linha);
                    i += 1;
                }
                br.close();
                fr.close();
            } catch (FileNotFoundException ex) {
                ex.printStackTrace();
            } catch (IOException ioe){
                ioe.printStackTrace();
            }
    }//GEN-LAST:event_btnMostrarDadosUserActionPerformed

    private void btnEditarDadosUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarDadosUserActionPerformed
        FormEditar fr = new FormEditar();
        this.setVisible(false);
        fr.setVisible(true);
    }//GEN-LAST:event_btnEditarDadosUserActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Login log = new Login();
        this.dispose();
        log.setVisible(true);
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnMostrarUsersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarUsersActionPerformed
        File ficheiro = new File("C:\\Users\\hpaulo\\Desktop\\ProjetoJava\\SistemasLogin2");
        File [] lista = ficheiro.listFiles();
        System.out.println("Lista de Utilizadores");
        for (File lista1 : lista) {
            if (lista1.getName().endsWith(".txt")) {
                System.out.println(lista1.getName().replace(".txt", ""));
            }
            
        }
    }//GEN-LAST:event_btnMostrarUsersActionPerformed

    private void btnEliminarUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarUserActionPerformed
        File ficheiro = new File(login+".txt");
        ficheiro.delete();
        System.out.println("UTILIZADOR ELIMINADO!");
        Login log = new Login();
        this.dispose();
        log.setVisible(true);                
    }//GEN-LAST:event_btnEliminarUserActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuOpcoes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuOpcoes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditarDadosUser;
    private javax.swing.JButton btnEliminarUser;
    private javax.swing.JButton btnMostrarDadosUser;
    private javax.swing.JButton btnMostrarUsers;
    private javax.swing.JButton btnSair;
    // End of variables declaration//GEN-END:variables
}
